import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "../components/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://use.typekit.net/zns7iwm.css" />
			</head>
			<body className={`${inter.variable}`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
